#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""导出每日新品数据到 SQL 文件"""

import sqlite3

DB_PATH = 'faam_products.db'
OUTPUT_FILE = 'daily_new_arrivals_data.sql'

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

# 导出每日新品数据为 SQL INSERT 语句
with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    f.write('-- Daily New Arrivals Data Export\n')
    f.write('-- Generated by export_daily_new.py\n\n')

    cursor.execute('''
        SELECT id, tcin, title, brand, price, image_url, product_url, date_detected, is_processed
        FROM daily_new_arrivals
    ''')

    for row in cursor.fetchall():
        values = []
        for val in row:
            if val is None:
                values.append('NULL')
            elif isinstance(val, str):
                # 转义单引号
                val_escaped = val.replace("'", "''")
                values.append(f"'{val_escaped}'")
            elif isinstance(val, float):
                values.append(str(val))
            else:
                values.append(str(val))

        sql = f"INSERT INTO daily_new_arrivals (id, tcin, title, brand, price, image_url, product_url, date_detected, is_processed) VALUES ({', '.join(values)});\n"
        f.write(sql)

# 统计
cursor.execute('SELECT COUNT(*) FROM daily_new_arrivals')
print(f'Exported {cursor.fetchone()[0]} records to {OUTPUT_FILE}')

conn.close()
